removed create-symlink: true due to below  error
  + ln -s /usr/bin/ccache /usr/local/bin/gcc
  ln: failed to create symbolic link '/usr/local/bin/gcc': File exists
  Error: Restoring cache failed: Error: The process '/usr/bin/sh' failed with exit code 1